name: problem-tracker-dev

services:
  database:
    container_name: oracledb
    image: container-registry.oracle.com/database/free:latest
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=
    volumes:
      - oracledb:/opt/oracle/oradata

volumes:
  oracledb: