ALTER SESSION SET CONTAINER = "FREEPDB1";

CREATE SEQUENCE PROBLEM_TRACKER.ROLE_SEQ
    MINVALUE 1
    MAXVALUE 99
    START WITH 1
    INCREMENT BY 1
    CACHE 5;

CREATE TABLE PROBLEM_TRACKER.ROLE (
    ID NUMBER(2) DEFAULT "PROBLEM_TRACKER"."ROLE_SEQ".nextval NOT NULL PRIMARY KEY,
    NAME VARCHAR2(32) NOT NULL
        CONSTRAINT ROLE_UK UNIQUE,
    CONSTRAINT ROLE_NAME_MIN CHECK (LENGTH(NAME) > 1),
    CONSTRAINT ROLE_ID_MIN CHECK (ID > 0));

INSERT INTO PROBLEM_TRACKER.ROLE (NAME) VALUES ('ADMIN');
INSERT INTO PROBLEM_TRACKER.ROLE (NAME) VALUES ('USER');