ALTER SESSION SET CONTAINER = "FREEPDB1";

CREATE USER PROBLEM_TRACKER_APP IDENTIFIED BY "Abc!1234"
    DEFAULT TABLESPACE USERS
;

GRANT CREATE SESSION TO PROBLEM_TRACKER_APP;

/* Grant table permissions to app. Note: / is needed for P/SQL */
BEGIN
    FOR t in (SELECT table_name FROM all_tables WHERE OWNER = 'PROBLEM_TRACKER')
        LOOP
            EXECUTE IMMEDIATE CONCAT(CONCAT('GRANT SELECT, UPDATE, DELETE, INSERT ON "PROBLEM_TRACKER"."', t.TABLE_NAME), '" TO PROBLEM_TRACKER_APP');
        END LOOP;
END;
/

/* Grant sequence permissions to app. Note: / is needed for P/SQL */
BEGIN
    FOR s in (SELECT SEQUENCE_NAME FROM ALL_SEQUENCES WHERE SEQUENCE_OWNER = 'PROBLEM_TRACKER')
        LOOP
            EXECUTE IMMEDIATE CONCAT(CONCAT('GRANT SELECT ON "PROBLEM_TRACKER"."', s.SEQUENCE_NAME), '" TO PROBLEM_TRACKER_APP');
        END LOOP;
END;
/