spring.application.name=service-discovery
spring.config.import=optional:configserver:http://${CONFIG_HOST:localhost}:${CONFIG_PORT:8071}
spring.cloud.loadbalancer.enabled=false
spring.profiles.active=default