GRANT CREATE SESSION TO PROBLEM_TRACKER_APP;

GRANT SELECT, INSERT, UPDATE, DELETE ON PROBLEM_TRACKER.CATEGORY TO PROBLEM_TRACKER_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON PROBLEM_TRACKER.DIFFICULTY TO PROBLEM_TRACKER_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON PROBLEM_TRACKER.PLATFORM TO PROBLEM_TRACKER_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON PROBLEM_TRACKER.ROLE TO PROBLEM_TRACKER_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON PROBLEM_TRACKER.PROGRAMMING_LANGUAGE TO PROBLEM_TRACKER_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON PROBLEM_TRACKER.PROBLEM TO PROBLEM_TRACKER_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON PROBLEM_TRACKER."USER" TO PROBLEM_TRACKER_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON PROBLEM_TRACKER.PROBLEM_CATEGORY TO PROBLEM_TRACKER_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON PROBLEM_TRACKER.ENVIRONMENT TO PROBLEM_TRACKER_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON PROBLEM_TRACKER.USER_PROBLEM TO PROBLEM_TRACKER_APP;

GRANT SELECT ON PROBLEM_TRACKER.CATEGORY_SEQ TO PROBLEM_TRACKER_APP;
GRANT SELECT ON PROBLEM_TRACKER.DIFFICULTY_SEQ TO PROBLEM_TRACKER_APP;
GRANT SELECT ON PROBLEM_TRACKER.PLATFORM_SEQ TO PROBLEM_TRACKER_APP;
GRANT SELECT ON PROBLEM_TRACKER.ROLE_SEQ TO PROBLEM_TRACKER_APP;
GRANT SELECT ON PROBLEM_TRACKER.PROGRAMMING_LANGUAGE_SEQ TO PROBLEM_TRACKER_APP;
GRANT SELECT ON PROBLEM_TRACKER.PROBLEM_SEQ TO PROBLEM_TRACKER_APP;
GRANT SELECT ON PROBLEM_TRACKER.USER_SEQ TO PROBLEM_TRACKER_APP;
GRANT SELECT ON PROBLEM_TRACKER.ENVIRONMENT_SEQ TO PROBLEM_TRACKER_APP;
GRANT SELECT ON PROBLEM_TRACKER.USER_PROBLEM_SEQ TO PROBLEM_TRACKER_APP;