ALTER USER PROBLEM_TRACKER IDENTIFIED BY "Abc!1234";

GRANT
    CREATE VIEW,
    CREATE PROCEDURE,
    CREATE TABLE,
    CREATE SESSION,
    CREATE SEQUENCE,
    CREATE TRIGGER,
    CREATE TYPE,
    UNLIMITED TABLESPACE
TO PROBLEM_TRACKER;
