ALTER SESSION SET CONTAINER = "FREEPDB1";

CREATE USER PROBLEM_TRACKER IDENTIFIED BY "Abc!1234"
    DEFAULT TABLESPACE USERS;

GRANT
    CREATE VIEW,
    CREATE PROCEDURE,
    CREATE TABLE,
    CREATE SESSION,
    CREATE SEQUENCE,
    CREATE TRIGGER,
    CREATE TYPE,
    UNLIMITED TABLESPACE
TO PROBLEM_TRACKER;