ALTER SESSION SET CONTAINER = "FREEPDB1";

CREATE SEQUENCE PROBLEM_TRACKER.PLATFORM_SEQ
    MINVALUE 1
    MAXVALUE 999
    START WITH 1
    INCREMENT BY 1
    CACHE 20;

CREATE TABLE PROBLEM_TRACKER.PLATFORM
(
    ID   NUMBER(3) DEFAULT PROBLEM_TRACKER.PLATFORM_SEQ.NEXTVAL
        CONSTRAINT PLATFORM_PK
            PRIMARY KEY,
    NAME VARCHAR2(128) NOT NULL
        CONSTRAINT PLATFORM_PK_2
            UNIQUE,
    DOMAIN VARCHAR2(32) NOT NULL
        CONSTRAINT PLATFORM_DOMAIN_UK
            UNIQUE,
    CONSTRAINT PLATFORM_ID_MIN_VALUE CHECK (ID > 0),
    CONSTRAINT PLATFORM_NAME_MIN_LENGTH CHECK (LENGTH(NAME) >= 2),
    /* Don't want to add a scheme, just want the domain */
    CONSTRAINT PLATFORM_DOMAIN_NO_SCHEME CHECK (DOMAIN NOT LIKE 'http' AND DOMAIN NOT LIKE '%:%' AND DOMAIN NOT LIKE '%/%'),
    CONSTRAINT PLATFORM_DOMAIN_MIN_LENGTH CHECK (LENGTH(DOMAIN) >= 3),
    CONSTRAINT PLATFORM_DOMAIN_CONTAINS_DOT CHECK (DOMAIN LIKE '%.%'));

INSERT INTO PROBLEM_TRACKER.PLATFORM (NAME, DOMAIN) VALUES ('Leetcode', 'leetcode.com');
INSERT INTO PROBLEM_TRACKER.PLATFORM (NAME, DOMAIN) VALUES ('HackerRank', 'hackerrank.com');
INSERT INTO PROBLEM_TRACKER.PLATFORM (NAME, DOMAIN) VALUES ('Algo Monster', 'algo.monster');
