ALTER SESSION SET CONTAINER = "FREEPDB1";

CREATE SEQUENCE PROBLEM_TRACKER.USER_SEQ
    MINVALUE 1
    MAXVALUE 999999999999
    START WITH 1
    INCREMENT BY 1
    CACHE 10;

CREATE TABLE PROBLEM_TRACKER."USER"
(
    ID            NUMBER(12)    DEFAULT PROBLEM_TRACKER.USER_SEQ.NEXTVAL
        CONSTRAINT USER_PK
            PRIMARY KEY,
    EMAIL_ADDRESS VARCHAR2(255)                           NOT NULL
        CONSTRAINT USER_PK_2
            UNIQUE,
    ROLE_ID       NUMBER(2)                               NOT NULL
        CONSTRAINT USER_ROLE_ID_FK
            REFERENCES PROBLEM_TRACKER.ROLE (ID)
                ON DELETE CASCADE,
    CREATED_ON    TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PASSWORD_HASH VARCHAR2(128) NOT NULL,
    ENABLED       BOOLEAN       DEFAULT TRUE              NOT NULL,
    LOCKED        BOOLEAN       DEFAULT FALSE             NOT NULL,
    CONSTRAINT USER_ID_MIN_VALUE CHECK (ID > 0),
    CONSTRAINT USER_EMAIL_MIN_LENGTH CHECK (LENGTH(EMAIL_ADDRESS) >= 5),
    CONSTRAINT USER_EMAIL_MAX_LENGTH CHECK (LENGTH(EMAIL_ADDRESS) <= 255),
    CONSTRAINT USER_EMAIL_PATTERN CHECK (REGEXP_LIKE(EMAIL_ADDRESS, '^[a-zA-Z0-9]+(\.?[a-zA-Z0-9]+)*@[a-zA-Z0-9]+(\.[a-zA-Z0-9]+)+$', 'i')),
    CONSTRAINT USER_PASSWORD_HASH_MIN_LENGTH CHECK (LENGTH(PASSWORD_HASH) >= 16),
    CONSTRAINT USER_CREATED_ON_AFTER_PROJECT_CREATION CHECK (CREATED_ON > TIMESTAMP '2026-07-13 00:00:00'));

/* Password is Abc!1234 */
INSERT INTO PROBLEM_TRACKER."USER" (EMAIL_ADDRESS, ROLE_ID, PASSWORD_HASH) VALUES ('test.user@test.com', (SELECT ID FROM PROBLEM_TRACKER.ROLE WHERE NAME = 'USER'), '$2a$10$nLMbY0snzujqM7eqcJIQiOWJlTV2APQuZQr/zNEyBh02KIu4KtxMy');
INSERT INTO PROBLEM_TRACKER."USER" (EMAIL_ADDRESS, ROLE_ID, PASSWORD_HASH) VALUES ('test.admin@test.com', (SELECT ID FROM PROBLEM_TRACKER.ROLE WHERE NAME = 'ADMIN'), '$2a$10$nLMbY0snzujqM7eqcJIQiOWJlTV2APQuZQr/zNEyBh02KIu4KtxMy');