ALTER SESSION SET CONTAINER = "FREEPDB1";

CREATE TABLE PROBLEM_TRACKER.PROBLEM_CATEGORY
(
    PROBLEM_ID  NUMBER(9) NOT NULL
        CONSTRAINT PROBLEMS_CATEGORY_PROBLEMS_ID_FK
            REFERENCES PROBLEM_TRACKER.PROBLEM
                ON DELETE CASCADE,
    CATEGORY_ID NUMBER(3) NOT NULL
        CONSTRAINT PROBLEMS_CATEGORY_CATEGORY_ID_FK
            REFERENCES PROBLEM_TRACKER.CATEGORY
                ON DELETE CASCADE,
    CONSTRAINT PROBLEMS_CATEGORY_PK
        PRIMARY KEY (PROBLEM_ID, CATEGORY_ID));