ALTER SESSION SET CONTAINER = "FREEPDB1";

CREATE SEQUENCE PROBLEM_TRACKER.USER_PROBLEM_SEQ
    MINVALUE 1
    MAXVALUE 999999999999999
    START WITH 1
    INCREMENT BY 1
    CACHE 30;

CREATE TABLE PROBLEM_TRACKER.USER_PROBLEM
(
    ID                      NUMBER(15) DEFAULT PROBLEM_TRACKER.USER_PROBLEM_SEQ.NEXTVAL
        CONSTRAINT USER_PROBLEMS_PK
            PRIMARY KEY,
    USER_ID                 NUMBER(12)   NOT NULL
        CONSTRAINT USER_PROBLEMS_USER_ID_FK
            REFERENCES PROBLEM_TRACKER."USER"
                ON DELETE CASCADE,
    PROBLEM_ID              NUMBER(8)    NOT NULL
        CONSTRAINT USER_PROBLEMS_PROBLEM_ID_FK
            REFERENCES PROBLEM_TRACKER.PROBLEM
                ON DELETE CASCADE,
    SOLVED_ON               TIMESTAMP(6) NOT NULL,
    MINUTES                 NUMBER(5, 2) NOT NULL,
    PROGRAMMING_LANGUAGE_ID NUMBER(4)    NOT NULL
        CONSTRAINT USER_PROBLEMS_PROGRAMMING_LANGUAGE_ID_FK
            REFERENCES PROBLEM_TRACKER.PROGRAMMING_LANGUAGE
                ON DELETE CASCADE,
    CONSTRAINT USER_PROBLEM_MIN_ID_VALUE CHECK (ID > 0),
    CONSTRAINT USER_PROBLEM_SOLVED_ON_AFTER_FIRST_OF_YEAR_2026 CHECK (SOLVED_ON > TIMESTAMP '2026-01-01 00:00:00'),
    CONSTRAINT USER_PROBLEM_MINUTES_MIN_VALUE CHECK (MINUTES > 0),
    CONSTRAINT USER_PROBLEM_MINUTES_MAX_VALUE CHECK (MINUTES <= 999));
