spring.application.name=problem-service
spring.web.error.include-stacktrace=never
spring.web.error.whitelabel.enabled=false
spring.profiles.active=dev

# Database Configuration
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver