# Database Connection Settings
hibernate.connection.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1
hibernate.username=PROBLEM_TRACKER
hibernate.password=Abc!1234
hibernate.connection.driver_class=oracle.jdbc.OracleDriver

# Database Configuration
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.highlight_sql=true