spring.application.name=account-service
spring.web.error.include-stacktrace=never
spring.web.error.whitelabel.enabled=false

# Database Configuration
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.jpa.properties.hibernate.default_schema=PROBLEM_TRACKER
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver

server.port=8081

# Discovery
eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=

# Auth
jwt.key=
jwt.algorithm=HmacSHA256

# Actuator Config
management.endpoints.web.exposure.include=health