server.port=8072

# Discovery
eureka.client.service-url.defaultZone=http://localhost:8070/eureka/

# Auth
jwt.key=CAcCrFzykqzskkN4y7Lyf6EnfuEBH3EN

# Database Configuration
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1
spring.datasource.username=PROBLEM_TRACKER
spring.datasource.password=Abc!1234
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver