spring.application.name=problem-gateway
spring.web.error.include-stacktrace=never
spring.web.error.whitelabel.enabled=false

server.port=8072

# Discovery
eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=

# Auth
jwt.key=
jwt.issuer=Problem Tracker
jwt.algorithm=HmacSHA256
jwt.hours-valid=24

# Database Configuration
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver

# Actuator Config
management.endpoints.web.exposure.include=health