CREATE SEQUENCE CATEGORY_SEQ
    MINVALUE 1
    MAXVALUE 999
    START WITH 1
    INCREMENT BY 1
    CACHE 25;

CREATE TABLE PROBLEM_TRACKER.CATEGORY
(
    ID   NUMBER(3) DEFAULT "PROBLEM_TRACKER"."CATEGORY_SEQ".NEXTVAL
		CONSTRAINT CATEGORY_PK
			PRIMARY KEY,
    NAME VARCHAR2(128) NOT NULL
        CONSTRAINT CATEGORY_UK
            UNIQUE,

    CONSTRAINT CATEGORY_ID_MIN_VALUE CHECK (ID > 0),
    CONSTRAINT CATEGORY_NAME_MIN_LENGTH CHECK (LENGTH(NAME) >= 2)
)
/

INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('String');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Set');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('HashMap');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Queue');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Stack');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Binary Search');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Array');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Sorting');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Linked List');
