CREATE SEQUENCE CATEGORY_SEQ
    MINVALUE 1
    MAXVALUE 999
    START WITH 1
    INCREMENT BY 1
    CACHE 25;

CREATE TABLE PROBLEM_TRACKER.CATEGORY
(
    ID   NUMBER(3) DEFAULT "PROBLEM_TRACKER"."CATEGORY_SEQ".NEXTVAL
		CONSTRAINT CATEGORY_PK
			PRIMARY KEY,
    NAME VARCHAR2(128) NOT NULL
        CONSTRAINT CATEGORY_UK
            UNIQUE,

    CONSTRAINT CATEGORY_ID_MIN_VALUE CHECK (ID > 0),
    CONSTRAINT CATEGORY_NAME_MIN_LENGTH CHECK (LENGTH(NAME) >= 2)
);

INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Array');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('String');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Hash Table');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Math');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Dynamic Programming');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Sorting');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Greedy');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Depth-First Search');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Binary Search');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Database');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Bit Manipulation');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Matrix');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Tree');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Prefix Sum');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Breadth-First Search');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Two Pointers');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Heap (Priority Queue)');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Simulation');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Counting');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Graph Theory');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Binary Tree');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Stack');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Sliding Window');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Enumeration');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Design');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Backtracking');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Number Theory');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Union-Find');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Linked List');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Segment Tree');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Ordered Set');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Monotonic Stack');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Divide and Conquer');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Combinatorics');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Trie');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Queue');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Bitmask');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Recursion');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Geometry');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Binary Indexed Tree');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Hash Function');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Memoization');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Binary Search Tree');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Shortest Path');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Topological Sort');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('String Matching');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Rolling Hash');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Game Theory');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Monotonic Queue');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Interactive');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Data Stream');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Brainteaser');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Doubly-Linked List');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Merge Sort');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Randomized');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Counting Sort');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Iterator');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Concurrency');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Quickselect');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Suffix Array');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Sweep Line');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Probability and Statistics');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Minimum Spanning Tree');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Bucket Sort');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Shell');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Reservoir Sampling');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Eulerian Circuit');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Radix Sort');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Strongly Connected Component');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Rejection Sampling');
INSERT INTO PROBLEM_TRACKER.CATEGORY (NAME) VALUES ('Biconnected Component');
