CREATE SEQUENCE DIFFICULTY_SEQ
    MINVALUE 1
    MAXVALUE 99
    START WITH 1
    INCREMENT BY 1
    CACHE 10;

CREATE TABLE DIFFICULTY
(
    ID   NUMBER(2) DEFAULT "PROBLEM_TRACKER"."DIFFICULTY_SEQ".NEXTVAL
        CONSTRAINT DIFFICULTY_PK
            PRIMARY KEY,
    NAME VARCHAR2(128) NOT NULL
        CONSTRAINT DIFFICULTY_UK
            UNIQUE

    CONSTRAINT ID_MIN_VALUE CHECK (ID > 0)
    CONSTRAINT NAME_MIN_LENGTH CHECK (LENGTH(NAME) >= 2)
)
/

INSERT INTO PROBLEM_TRACKER.DIFFICULTY (NAME) VALUES ('Easy');
INSERT INTO PROBLEM_TRACKER.DIFFICULTY (NAME) VALUES ('Medium');
INSERT INTO PROBLEM_TRACKER.DIFFICULTY (NAME) VALUES ('Hard');
