CREATE SEQUENCE PLATFORM_SEQ
    MINVALUE 1
    MAXVALUE 999
    START WITH 1
    INCREMENT BY 1
    CACHE 20;

CREATE TABLE PLATFORM
(
    ID   NUMBER(3) DEFAULT "PROBLEM_TRACKER"."PLATFORM_SEQ".NEXTVAL
        CONSTRAINT PLATFORM_PK
            PRIMARY KEY,
    NAME VARCHAR2(128) NOT NULL
        CONSTRAINT PLATFORM_PK_2
            UNIQUE

    CONSTRAINT ID_MIN_VALUE CHECK (ID > 0)
    CONSTRAINT NAME_MIN_LENGTH CHECK (LENGTH(NAME) >= 2)
)
/

INSERT INTO PROBLEM_TRACKER.PLATFORM (ID, NAME) VALUES (21, 'Leetcode');
INSERT INTO PROBLEM_TRACKER.PLATFORM (ID, NAME) VALUES (22, 'HackerRank');
INSERT INTO PROBLEM_TRACKER.PLATFORM (ID, NAME) VALUES (23, 'Algo Monster');
