CREATE SEQUENCE PLATFORM_SEQ
    MINVALUE 1
    MAXVALUE 999
    START WITH 1
    INCREMENT BY 1
    CACHE 20;

CREATE TABLE PLATFORM
(
    ID   NUMBER(3) DEFAULT "PROBLEM_TRACKER"."PLATFORM_SEQ".NEXTVAL
        CONSTRAINT PLATFORM_PK
            PRIMARY KEY,
    NAME VARCHAR2(128) NOT NULL
        CONSTRAINT PLATFORM_PK_2
            UNIQUE,

    CONSTRAINT PLATFORM_ID_MIN_VALUE CHECK (ID > 0),
    CONSTRAINT PLATFORM_NAME_MIN_LENGTH CHECK (LENGTH(NAME) >= 2)
)
/

INSERT INTO PROBLEM_TRACKER.PLATFORM (NAME) VALUES ('Leetcode');
INSERT INTO PROBLEM_TRACKER.PLATFORM (NAME) VALUES ('HackerRank');
INSERT INTO PROBLEM_TRACKER.PLATFORM (NAME) VALUES ('Algo Monster');
