CREATE SEQUENCE PROBLEM_SEQ
    MINVALUE 1
    MAXVALUE 999999999
    START WITH 1
    INCREMENT BY 1
    CACHE 30;

CREATE TABLE PROBLEM
(
    ID            NUMBER(9) DEFAULT "PROBLEM_TRACKER"."PROBLEM_SEQ".NEXTVAL
		CONSTRAINT PROBLEM_PK
			PRIMARY KEY,
    NAME          VARCHAR2(128)       NOT NULL,
    URL           VARCHAR2(512)       NOT NULL,
    PLATFORM_ID   NUMBER(3) DEFAULT 0 NOT NULL
        CONSTRAINT PROBLEM_PLATFORM_ID_FK
            REFERENCES PLATFORM
                ON DELETE CASCADE,
    DIFFICULTY_ID NUMBER(2) DEFAULT 0 NOT NULL
        CONSTRAINT PROBLEM_DIFFICULTY_ID_FK
            REFERENCES DIFFICULTY
                ON DELETE CASCADE,

    CONSTRAINT PROBLEM_ID_MIN_VALUE CHECK (ID > 0),
    CONSTRAINT PROBLEM_NAME_MIN_LENGTH CHECK (LENGTH(NAME) >= 2),
    CONSTRAINT PROBLEM_URL_MIN_LENGTH CHECK (LENGTH(URL) >= 10)
)
/

