CREATE SEQUENCE PROGRAMMING_LANGUAGE_SEQ
    MINVALUE 1
    MAXVALUE 9999
    START WITH 1
    INCREMENT BY 1
    CACHE 10;

CREATE TABLE PROGRAMMING_LANGUAGE
(
    ID   NUMBER(4) DEFAULT "PROBLEM_TRACKER"."PROGRAMMING_LANGUAGE_SEQ".NEXTVAL
        CONSTRAINT PROGRAMMING_LANGUAGE_PK
            PRIMARY KEY,
    NAME VARCHAR2(128) NOT NULL
        CONSTRAINT PROGRAMMING_LANGUAGE_PK_2
            UNIQUE,

    CONSTRAINT PROGRAMMING_LANGUAGE_ID_MIN_VALUE CHECK (ID > 0),
    CONSTRAINT PROGRAMMING_LANGUAGE_NAME_MIN_LENGTH CHECK (LENGTH(NAME) >= 1)
);

INSERT INTO PROBLEM_TRACKER.PROGRAMMING_LANGUAGE (NAME) VALUES ('C++');
INSERT INTO PROBLEM_TRACKER.PROGRAMMING_LANGUAGE (NAME) VALUES ('Java');
INSERT INTO PROBLEM_TRACKER.PROGRAMMING_LANGUAGE (NAME) VALUES ('Python3');
INSERT INTO PROBLEM_TRACKER.PROGRAMMING_LANGUAGE (NAME) VALUES ('Python');
INSERT INTO PROBLEM_TRACKER.PROGRAMMING_LANGUAGE (NAME) VALUES ('JavaScript');
INSERT INTO PROBLEM_TRACKER.PROGRAMMING_LANGUAGE (NAME) VALUES ('TypeScript');
INSERT INTO PROBLEM_TRACKER.PROGRAMMING_LANGUAGE (NAME) VALUES ('C#');
INSERT INTO PROBLEM_TRACKER.PROGRAMMING_LANGUAGE (NAME) VALUES ('C');
INSERT INTO PROBLEM_TRACKER.PROGRAMMING_LANGUAGE (NAME) VALUES ('Go');
INSERT INTO PROBLEM_TRACKER.PROGRAMMING_LANGUAGE (NAME) VALUES ('Kotlin');
INSERT INTO PROBLEM_TRACKER.PROGRAMMING_LANGUAGE (NAME) VALUES ('Swift');
INSERT INTO PROBLEM_TRACKER.PROGRAMMING_LANGUAGE (NAME) VALUES ('Rust');
INSERT INTO PROBLEM_TRACKER.PROGRAMMING_LANGUAGE (NAME) VALUES ('Ruby');
INSERT INTO PROBLEM_TRACKER.PROGRAMMING_LANGUAGE (NAME) VALUES ('PHP');
INSERT INTO PROBLEM_TRACKER.PROGRAMMING_LANGUAGE (NAME) VALUES ('Dart');
INSERT INTO PROBLEM_TRACKER.PROGRAMMING_LANGUAGE (NAME) VALUES ('Scala');
INSERT INTO PROBLEM_TRACKER.PROGRAMMING_LANGUAGE (NAME) VALUES ('Elixir');
INSERT INTO PROBLEM_TRACKER.PROGRAMMING_LANGUAGE (NAME) VALUES ('Erlang');
INSERT INTO PROBLEM_TRACKER.PROGRAMMING_LANGUAGE (NAME) VALUES ('Racket');
