CREATE SEQUENCE PROGRAMMING_LANGUAGE_SEQ
    MINVALUE 1
    MAXVALUE 9999
    START WITH 1
    INCREMENT BY 1
    CACHE 10;

CREATE TABLE PROGRAMMING_LANGUAGE
(
    ID   NUMBER(4) DEFAULT "PROBLEM_TRACKER"."PROGRAMMING_LANGUAGE_SEQ".NEXTVAL
        CONSTRAINT PROGRAMMING_LANGUAGE_PK
            PRIMARY KEY,
    NAME VARCHAR2(128) NOT NULL
        CONSTRAINT PROGRAMMING_LANGUAGE_PK_2
            UNIQUE

    CONSTRAINT ID_MIN_VALUE CHECK (ID > 0)
    CONSTRAINT NAME_MIN_LENGTH CHECK (LENGTH(NAME) >= 2)
)
/

INSERT INTO PROBLEM_TRACKER.PROGRAMMING_LANGUAGE (NAME) VALUES ('Java');
INSERT INTO PROBLEM_TRACKER.PROGRAMMING_LANGUAGE (NAME) VALUES ('JavaScript');
INSERT INTO PROBLEM_TRACKER.PROGRAMMING_LANGUAGE (NAME) VALUES ('TypeScript');
INSERT INTO PROBLEM_TRACKER.PROGRAMMING_LANGUAGE (NAME) VALUES ('Python');
