CREATE SEQUENCE USER_PROBLEM_SEQ
    MINVALUE 1
    MAXVALUE 999999999999999
    START WITH 1
    INCREMENT BY 1
    CACHE 30;

CREATE TABLE USER_PROBLEM
(
    ID                      NUMBER(15)   DEFAULT "PROBLEM_TRACKER"."USER_PROBLEM_SEQ".NEXTVAL
		CONSTRAINT USER_PROBLEMS_PK
			PRIMARY KEY,
    USER_ID                 NUMBER(12)             NOT NULL
        CONSTRAINT USER_PROBLEMS_USER_ID_FK
            REFERENCES "USER"
                ON DELETE CASCADE,
    PROBLEM_ID              NUMBER(8)              NOT NULL
        CONSTRAINT USER_PROBLEMS_PROBLEM_ID_FK
            REFERENCES PROBLEM
                ON DELETE CASCADE,
    SOLVED_ON               TIMESTAMP(6)           NOT NULL,
    MINUTES                 NUMBER(5, 2) DEFAULT 0 NOT NULL,
    PROGRAMMING_LANGUAGE_ID NUMBER(4)    DEFAULT 0 NOT NULL
        CONSTRAINT USER_PROBLEMS_PROGRAMMING_LANGUAGE_ID_FK
            REFERENCES PROGRAMMING_LANGUAGE
                ON DELETE CASCADE

    CONSTRAINT MIN_ID_VALUE CHECK (ID > 0)
    CONSTRAINT SOLVED_ON_AFTER_FIRST_OF_YEAR_2026 CHECK (SOLVED_ON > '2026-01-01 00:00:00')
    CONSTRAINT SOLVED_ON_NOT_IN_FUTURE CHECK (SOLVED_ON < SYSDATE)
    CONSTRAINT MINUTES_MIN_VALUE CHECK (MINUTES > 0)
    CONSTRAINT MINUTES_MAX_VALUE CHECK (MINUTES <= 999)
)
/

