CREATE SEQUENCE USER_PROBLEMS_SEQ
    MINVALUE 1
    MAXVALUE 999999999999999
    START WITH 1
    INCREMENT BY 1
    CACHE 30;

CREATE TABLE USER_PROBLEMS
(
    ID                      NUMBER(15)   DEFAULT "PROBLEM_TRACKER"."USER_PROBLEMS_SEQ".NEXTVAL
		CONSTRAINT USER_PROBLEMS_PK
			PRIMARY KEY,
    USER_ID                 NUMBER(12)             NOT NULL
        CONSTRAINT USER_PROBLEMS_USER_ID_FK
            REFERENCES "USER",
    PROBLEM_ID              NUMBER(8)              NOT NULL
        CONSTRAINT USER_PROBLEMS_PROBLEM_ID_FK
            REFERENCES PROBLEM,
    SOLVED_ON               TIMESTAMP(6)           NOT NULL,
    MINUTES                 NUMBER(3, 2) DEFAULT 0 NOT NULL,
    PROGRAMMING_LANGUAGE_ID NUMBER(4)    DEFAULT 0 NOT NULL
        CONSTRAINT USER_PROBLEMS_PROGRAMMING_LANGUAGE_ID_FK
            REFERENCES PROGRAMMING_LANGUAGE
)
/

