CREATE SEQUENCE USER_SEQ
    MINVALUE 1
    MAXVALUE 999999999999
    START WITH 1
    INCREMENT BY 1
    CACHE 10;

CREATE TABLE "USER"
(
    ID            NUMBER(12) DEFAULT "PROBLEM_TRACKER"."USER_SEQ".NEXTVAL
		CONSTRAINT USER_PK
			PRIMARY KEY,
    EMAIL_ADDRESS VARCHAR2(255)              NOT NULL
        CONSTRAINT USER_PK_2
            UNIQUE,
    CREATED_ON    TIMESTAMP(6)             NOT NULL,
    PASSWORD_HASH VARCHAR2(128)  DEFAULT NOT NULL,
    ENABLED       BOOLEAN    DEFAULT TRUE NOT NULL,
    LOCKED        BOOLEAN    DEFAULT FALSE NOT NULL

    CONSTRAINT ID_MIN_VALUE CHECK (ID > 0)
    CONSTRAINT EMAIL_MIN_LENGTH CHECK (LENGTH(EMAIL_ADDRESS) >= 5)
    CONSTRAINT EMAIL_MAX_LENGTH CHECK (LENGTH(EMAIL_ADDRESS) <= 255)
    CONSTRAINT PASSWORD_HASH_MIN_LENGTH CHECK (LENGTH(PASSWORD_HASH) >= 16)
    CONSTRAINT CREATED_ON_AFTER_PROJECT_CREATION CHECK (CREATED_ON > '2026-07-13 00:00:00')
    CONSTRAINT CREATED_ON_BEFORE_TODAY CHECK (CREATED_ON < SYSDATE)
)
/

