CREATE TABLE "USER"
(
    ID            NUMBER(12) GENERATED AS IDENTITY
		CONSTRAINT USER_PK
			PRIMARY KEY,
    EMAIL_ADDRESS VARCHAR2(256)              NOT NULL
        CONSTRAINT USER_PK_2
            UNIQUE,
    CREATED_ON    TIMESTAMP(6)             NOT NULL,
    PASSWORD_HASH VARCHAR2(128)  DEFAULT NOT NULL,
    ENABLED       BOOLEAN    DEFAULT TRUE,
    LOCKED        BOOLEAN    DEFAULT FALSE NOT NULL
)
/

