INSERT INTO CATEGORY (ID, NAME)
VALUES (NEXT VALUE FOR CATEGORY_SEQ, 'Array'),
       (NEXT VALUE FOR CATEGORY_SEQ, 'String'),
       (NEXT VALUE FOR CATEGORY_SEQ, 'Hash Table'),
       (NEXT VALUE FOR CATEGORY_SEQ, 'Dynamic Programming'),
       (NEXT VALUE FOR CATEGORY_SEQ, 'Sorting'),
       (NEXT VALUE FOR CATEGORY_SEQ, 'Greedy'),
       (NEXT VALUE FOR CATEGORY_SEQ, 'Depth-First Search'),
       (NEXT VALUE FOR CATEGORY_SEQ, 'Binary Search'),
       (NEXT VALUE FOR CATEGORY_SEQ, 'Database'),
       (NEXT VALUE FOR CATEGORY_SEQ, 'Bit Manipulation'),
       (NEXT VALUE FOR CATEGORY_SEQ, 'Matrix'),
       (NEXT VALUE FOR CATEGORY_SEQ, 'Tree'),
       (NEXT VALUE FOR CATEGORY_SEQ, 'Prefix Sum'),
       (NEXT VALUE FOR CATEGORY_SEQ, 'Breadth-First Search'),
       (NEXT VALUE FOR CATEGORY_SEQ, 'Two Pointers');

INSERT INTO DIFFICULTY
VALUES (NEXT VALUE FOR DIFFICULTY_SEQ, 'Easy'),
       (NEXT VALUE FOR DIFFICULTY_SEQ, 'Medium'),
       (NEXT VALUE FOR DIFFICULTY_SEQ, 'Hard');

INSERT INTO PLATFORM (ID, NAME, DOMAIN)
VALUES (NEXT VALUE FOR PLATFORM_SEQ, 'Leetcode', 'leetcode.com'),
       (NEXT VALUE FOR PLATFORM_SEQ, 'HackerRank', 'hackerrank.com'),
       (NEXT VALUE FOR PLATFORM_SEQ, 'Algo Monster', 'algo.monster');

INSERT INTO ROLE
VALUES (NEXT VALUE FOR ROLE_SEQ, 'ADMIN'),
       (NEXT VALUE FOR ROLE_SEQ, 'USER');

/** Password: Abc!1234 */
INSERT INTO "USER" (ID, EMAIL_ADDRESS, ROLE_ID, PASSWORD_HASH, ENABLED, LOCKED)
VALUES (NEXT VALUE FOR USER_SEQ, 'test.user@test.com', (SELECT ID FROM ROLE WHERE NAME = 'USER'),
        '$2a$10$nLMbY0snzujqM7eqcJIQiOWJlTV2APQuZQr/zNEyBh02KIu4KtxMy', TRUE, FALSE),
       (NEXT VALUE FOR USER_SEQ, 'test.admin@test.com', (SELECT ID FROM ROLE WHERE NAME = 'ADMIN'),
        '$2a$10$nLMbY0snzujqM7eqcJIQiOWJlTV2APQuZQr/zNEyBh02KIu4KtxMy', TRUE, FALSE);

INSERT INTO PROGRAMMING_LANGUAGE (ID, NAME)
VALUES (NEXT VALUE FOR PROGRAMMING_LANGUAGE_SEQ, 'C++'),
       (NEXT VALUE FOR PROGRAMMING_LANGUAGE_SEQ, 'Java'),
       (NEXT VALUE FOR PROGRAMMING_LANGUAGE_SEQ, 'Python3'),
       (NEXT VALUE FOR PROGRAMMING_LANGUAGE_SEQ, 'Python'),
       (NEXT VALUE FOR PROGRAMMING_LANGUAGE_SEQ, 'JavaScript'),
       (NEXT VALUE FOR PROGRAMMING_LANGUAGE_SEQ, 'TypeScript'),
       (NEXT VALUE FOR PROGRAMMING_LANGUAGE_SEQ, 'C#'),
       (NEXT VALUE FOR PROGRAMMING_LANGUAGE_SEQ, 'C'),
       (NEXT VALUE FOR PROGRAMMING_LANGUAGE_SEQ, 'Go'),
       (NEXT VALUE FOR PROGRAMMING_LANGUAGE_SEQ, 'Kotlin'),
       (NEXT VALUE FOR PROGRAMMING_LANGUAGE_SEQ, 'Swift'),
       (NEXT VALUE FOR PROGRAMMING_LANGUAGE_SEQ, 'Rust'),
       (NEXT VALUE FOR PROGRAMMING_LANGUAGE_SEQ, 'Ruby'),
       (NEXT VALUE FOR PROGRAMMING_LANGUAGE_SEQ, 'PHP'),
       (NEXT VALUE FOR PROGRAMMING_LANGUAGE_SEQ, 'Dart'),
       (NEXT VALUE FOR PROGRAMMING_LANGUAGE_SEQ, 'Scala'),
       (NEXT VALUE FOR PROGRAMMING_LANGUAGE_SEQ, 'Elixir'),
       (NEXT VALUE FOR PROGRAMMING_LANGUAGE_SEQ, 'Erlang'),
       (NEXT VALUE FOR PROGRAMMING_LANGUAGE_SEQ, 'Racket');

INSERT INTO PROBLEM (ID, NAME, URL, PLATFORM_ID, DIFFICULTY_ID)
VALUES (NEXT VALUE FOR PROBLEM_SEQ, 'Two Sum', 'https://leetcode.com/problems/two-sum/',
        (SELECT ID FROM PLATFORM WHERE NAME = 'Leetcode'), (SELECT ID FROM DIFFICULTY WHERE NAME = 'Easy')),
       (NEXT VALUE FOR PROBLEM_SEQ, 'Longest Substring Without Repeating Characters',
        'https://leetcode.com/problems/longest-substring-without-repeating-characters/',
        (SELECT ID FROM PLATFORM WHERE NAME = 'Leetcode'), (SELECT ID FROM DIFFICULTY WHERE NAME = 'Medium')),
       (NEXT VALUE FOR PROBLEM_SEQ, 'Median of Two Sorted Arrays',
        'https://leetcode.com/problems/median-of-two-sorted-arrays/', (SELECT ID FROM PLATFORM WHERE NAME = 'Leetcode'),
        (SELECT ID FROM DIFFICULTY WHERE NAME = 'Hard')),
       (NEXT VALUE FOR PROBLEM_SEQ, 'Climbing Stairs', 'https://leetcode.com/problems/climbing-stairs/',
        (SELECT ID FROM PLATFORM WHERE NAME = 'Leetcode'), (SELECT ID FROM DIFFICULTY WHERE NAME = 'Easy')),
       (NEXT VALUE FOR PROBLEM_SEQ, 'Course Schedule', 'https://leetcode.com/problems/course-schedule/',
        (SELECT ID FROM PLATFORM WHERE NAME = 'Leetcode'), (SELECT ID FROM DIFFICULTY WHERE NAME = 'Medium'));

INSERT INTO PROBLEM_CATEGORY (PROBLEM_ID, CATEGORY_ID)
VALUES ((SELECT ID FROM PROBLEM WHERE NAME = 'Two Sum'), (SELECT ID FROM CATEGORY WHERE NAME = 'Array')),
       ((SELECT ID FROM PROBLEM WHERE NAME = 'Two Sum'), (SELECT ID FROM CATEGORY WHERE NAME = 'Hash Table')),
       ((SELECT ID FROM PROBLEM WHERE NAME = 'Longest Substring Without Repeating Characters'),
        (SELECT ID FROM CATEGORY WHERE NAME = 'Hash Table')),
       ((SELECT ID FROM PROBLEM WHERE NAME = 'Longest Substring Without Repeating Characters'),
        (SELECT ID FROM CATEGORY WHERE NAME = 'String')),
       ((SELECT ID FROM PROBLEM WHERE NAME = 'Longest Substring Without Repeating Characters'),
        (SELECT ID FROM CATEGORY WHERE NAME = 'Two Pointers')),
       ((SELECT ID FROM PROBLEM WHERE NAME = 'Median of Two Sorted Arrays'),
        (SELECT ID FROM CATEGORY WHERE NAME = 'Array')),
       ((SELECT ID FROM PROBLEM WHERE NAME = 'Median of Two Sorted Arrays'),
        (SELECT ID FROM CATEGORY WHERE NAME = 'Binary Search')),
       ((SELECT ID FROM PROBLEM WHERE NAME = 'Climbing Stairs'),
        (SELECT ID FROM CATEGORY WHERE NAME = 'Dynamic Programming')),
       ((SELECT ID FROM PROBLEM WHERE NAME = 'Course Schedule'),
        (SELECT ID FROM CATEGORY WHERE NAME = 'Depth-First Search')),
       ((SELECT ID FROM PROBLEM WHERE NAME = 'Course Schedule'),
        (SELECT ID FROM CATEGORY WHERE NAME = 'Breadth-First Search'));

INSERT INTO ENVIRONMENT (ID, NAME)
VALUES (NEXT VALUE FOR ENVIRONMENT_SEQ, 'Pen and Paper'),
       (NEXT VALUE FOR ENVIRONMENT_SEQ, 'Whiteboard'),
       (NEXT VALUE FOR ENVIRONMENT_SEQ, 'Basic IDE'),
       (NEXT VALUE FOR ENVIRONMENT_SEQ, 'Full IDE'),
       (NEXT VALUE FOR ENVIRONMENT_SEQ, 'AI Assisted'),
       (NEXT VALUE FOR ENVIRONMENT_SEQ, 'Online Editor'),
       (NEXT VALUE FOR ENVIRONMENT_SEQ, 'Terminal');