INSERT INTO CATEGORY VALUES (NEXT VALUE FOR CATEGORY_SEQ, 'Array');
INSERT INTO CATEGORY VALUES (NEXT VALUE FOR CATEGORY_SEQ, 'String');
INSERT INTO CATEGORY VALUES (NEXT VALUE FOR CATEGORY_SEQ, 'Hash Table');
INSERT INTO CATEGORY VALUES (NEXT VALUE FOR CATEGORY_SEQ, 'Dynamic Programming');
INSERT INTO CATEGORY VALUES (NEXT VALUE FOR CATEGORY_SEQ, 'Sorting');
INSERT INTO CATEGORY VALUES (NEXT VALUE FOR CATEGORY_SEQ, 'Greedy');
INSERT INTO CATEGORY VALUES (NEXT VALUE FOR CATEGORY_SEQ, 'Depth-First Search');
INSERT INTO CATEGORY VALUES (NEXT VALUE FOR CATEGORY_SEQ, 'Binary Search');
INSERT INTO CATEGORY VALUES (NEXT VALUE FOR CATEGORY_SEQ, 'Database');
INSERT INTO CATEGORY VALUES (NEXT VALUE FOR CATEGORY_SEQ, 'Bit Manipulation');
INSERT INTO CATEGORY VALUES (NEXT VALUE FOR CATEGORY_SEQ, 'Matrix');
INSERT INTO CATEGORY VALUES (NEXT VALUE FOR CATEGORY_SEQ, 'Tree');
INSERT INTO CATEGORY VALUES (NEXT VALUE FOR CATEGORY_SEQ, 'Prefix Sum');
INSERT INTO CATEGORY VALUES (NEXT VALUE FOR CATEGORY_SEQ, 'Breadth-First Search');
INSERT INTO CATEGORY VALUES (NEXT VALUE FOR CATEGORY_SEQ, 'Two Pointers');

INSERT INTO DIFFICULTY VALUES (NEXT VALUE FOR DIFFICULTY_SEQ, 'Easy');
INSERT INTO DIFFICULTY VALUES (NEXT VALUE FOR DIFFICULTY_SEQ, 'Medium');
INSERT INTO DIFFICULTY VALUES (NEXT VALUE FOR DIFFICULTY_SEQ, 'Hard');

INSERT INTO PLATFORM (ID, NAME, DOMAIN) VALUES (NEXT VALUE FOR PLATFORM_SEQ, 'Leetcode', 'leetcode.com');
INSERT INTO PLATFORM (ID, NAME, DOMAIN) VALUES (NEXT VALUE FOR PLATFORM_SEQ, 'HackerRank', 'hackerrank.com');
INSERT INTO PLATFORM (ID, NAME, DOMAIN) VALUES (NEXT VALUE FOR PLATFORM_SEQ, 'Algo Monster', 'algo.monster');

INSERT INTO ROLE VALUES (NEXT VALUE FOR ROLE_SEQ, 'ADMIN');
INSERT INTO ROLE VALUES (NEXT VALUE FOR ROLE_SEQ, 'USER');

/** Password: Abc!1234 */
INSERT INTO "USER" (ID, EMAIL_ADDRESS, ROLE_ID, PASSWORD_HASH, ENABLED, LOCKED) VALUES (NEXT VALUE FOR USER_SEQ, 'test.user@test.com', (SELECT ID FROM ROLE WHERE NAME = 'USER'), '$2a$10$nLMbY0snzujqM7eqcJIQiOWJlTV2APQuZQr/zNEyBh02KIu4KtxMy', TRUE, FALSE);
INSERT INTO "USER" (ID, EMAIL_ADDRESS, ROLE_ID, PASSWORD_HASH, ENABLED, LOCKED) VALUES (NEXT VALUE FOR USER_SEQ, 'test.admin@test.com', (SELECT ID FROM ROLE WHERE NAME = 'ADMIN'), '$2a$10$nLMbY0snzujqM7eqcJIQiOWJlTV2APQuZQr/zNEyBh02KIu4KtxMy', TRUE, FALSE);

INSERT INTO PROGRAMMING_LANGUAGE (ID, NAME) VALUES (NEXT VALUE FOR PROGRAMMING_LANGUAGE_SEQ, 'C++');
INSERT INTO PROGRAMMING_LANGUAGE (ID, NAME) VALUES (NEXT VALUE FOR PROGRAMMING_LANGUAGE_SEQ, 'Java');
INSERT INTO PROGRAMMING_LANGUAGE (ID, NAME) VALUES (NEXT VALUE FOR PROGRAMMING_LANGUAGE_SEQ, 'Python3');
INSERT INTO PROGRAMMING_LANGUAGE (ID, NAME) VALUES (NEXT VALUE FOR PROGRAMMING_LANGUAGE_SEQ, 'Python');
INSERT INTO PROGRAMMING_LANGUAGE (ID, NAME) VALUES (NEXT VALUE FOR PROGRAMMING_LANGUAGE_SEQ, 'JavaScript');
INSERT INTO PROGRAMMING_LANGUAGE (ID, NAME) VALUES (NEXT VALUE FOR PROGRAMMING_LANGUAGE_SEQ, 'TypeScript');
INSERT INTO PROGRAMMING_LANGUAGE (ID, NAME) VALUES (NEXT VALUE FOR PROGRAMMING_LANGUAGE_SEQ, 'C#');
INSERT INTO PROGRAMMING_LANGUAGE (ID, NAME) VALUES (NEXT VALUE FOR PROGRAMMING_LANGUAGE_SEQ, 'C');
INSERT INTO PROGRAMMING_LANGUAGE (ID, NAME) VALUES (NEXT VALUE FOR PROGRAMMING_LANGUAGE_SEQ, 'Go');
INSERT INTO PROGRAMMING_LANGUAGE (ID, NAME) VALUES (NEXT VALUE FOR PROGRAMMING_LANGUAGE_SEQ, 'Kotlin');
INSERT INTO PROGRAMMING_LANGUAGE (ID, NAME) VALUES (NEXT VALUE FOR PROGRAMMING_LANGUAGE_SEQ, 'Swift');
INSERT INTO PROGRAMMING_LANGUAGE (ID, NAME) VALUES (NEXT VALUE FOR PROGRAMMING_LANGUAGE_SEQ, 'Rust');
INSERT INTO PROGRAMMING_LANGUAGE (ID, NAME) VALUES (NEXT VALUE FOR PROGRAMMING_LANGUAGE_SEQ, 'Ruby');
INSERT INTO PROGRAMMING_LANGUAGE (ID, NAME) VALUES (NEXT VALUE FOR PROGRAMMING_LANGUAGE_SEQ, 'PHP');
INSERT INTO PROGRAMMING_LANGUAGE (ID, NAME) VALUES (NEXT VALUE FOR PROGRAMMING_LANGUAGE_SEQ, 'Dart');
INSERT INTO PROGRAMMING_LANGUAGE (ID, NAME) VALUES (NEXT VALUE FOR PROGRAMMING_LANGUAGE_SEQ, 'Scala');
INSERT INTO PROGRAMMING_LANGUAGE (ID, NAME) VALUES (NEXT VALUE FOR PROGRAMMING_LANGUAGE_SEQ, 'Elixir');
INSERT INTO PROGRAMMING_LANGUAGE (ID, NAME) VALUES (NEXT VALUE FOR PROGRAMMING_LANGUAGE_SEQ, 'Erlang');
INSERT INTO PROGRAMMING_LANGUAGE (ID, NAME) VALUES (NEXT VALUE FOR PROGRAMMING_LANGUAGE_SEQ, 'Racket');

INSERT INTO PROBLEM (ID, NAME, URL, PLATFORM_ID, DIFFICULTY_ID) VALUES (NEXT VALUE FOR PROBLEM_SEQ, 'Two Sum', 'https://leetcode.com/problems/two-sum/', (SELECT ID FROM PLATFORM WHERE NAME = 'Leetcode'), (SELECT ID FROM DIFFICULTY WHERE NAME = 'Easy'));
INSERT INTO PROBLEM (ID, NAME, URL, PLATFORM_ID, DIFFICULTY_ID) VALUES (NEXT VALUE FOR PROBLEM_SEQ, 'Longest Substring Without Repeating Characters', 'https://leetcode.com/problems/longest-substring-without-repeating-characters/', (SELECT ID FROM PLATFORM WHERE NAME = 'Leetcode'), (SELECT ID FROM DIFFICULTY WHERE NAME = 'Medium'));
INSERT INTO PROBLEM (ID, NAME, URL, PLATFORM_ID, DIFFICULTY_ID) VALUES (NEXT VALUE FOR PROBLEM_SEQ, 'Median of Two Sorted Arrays', 'https://leetcode.com/problems/median-of-two-sorted-arrays/', (SELECT ID FROM PLATFORM WHERE NAME = 'Leetcode'), (SELECT ID FROM DIFFICULTY WHERE NAME = 'Hard'));
INSERT INTO PROBLEM (ID, NAME, URL, PLATFORM_ID, DIFFICULTY_ID) VALUES (NEXT VALUE FOR PROBLEM_SEQ, 'Climbing Stairs', 'https://leetcode.com/problems/climbing-stairs/', (SELECT ID FROM PLATFORM WHERE NAME = 'Leetcode'), (SELECT ID FROM DIFFICULTY WHERE NAME = 'Easy'));
INSERT INTO PROBLEM (ID, NAME, URL, PLATFORM_ID, DIFFICULTY_ID) VALUES (NEXT VALUE FOR PROBLEM_SEQ, 'Course Schedule', 'https://leetcode.com/problems/course-schedule/', (SELECT ID FROM PLATFORM WHERE NAME = 'Leetcode'), (SELECT ID FROM DIFFICULTY WHERE NAME = 'Medium'));

INSERT INTO PROBLEM_CATEGORY (PROBLEM_ID, CATEGORY_ID) VALUES ((SELECT ID FROM PROBLEM WHERE NAME = 'Two Sum'), (SELECT ID FROM CATEGORY WHERE NAME = 'Array'));
INSERT INTO PROBLEM_CATEGORY (PROBLEM_ID, CATEGORY_ID) VALUES ((SELECT ID FROM PROBLEM WHERE NAME = 'Two Sum'), (SELECT ID FROM CATEGORY WHERE NAME = 'Hash Table'));
INSERT INTO PROBLEM_CATEGORY (PROBLEM_ID, CATEGORY_ID) VALUES ((SELECT ID FROM PROBLEM WHERE NAME = 'Longest Substring Without Repeating Characters'), (SELECT ID FROM CATEGORY WHERE NAME = 'Hash Table'));
INSERT INTO PROBLEM_CATEGORY (PROBLEM_ID, CATEGORY_ID) VALUES ((SELECT ID FROM PROBLEM WHERE NAME = 'Longest Substring Without Repeating Characters'), (SELECT ID FROM CATEGORY WHERE NAME = 'String'));
INSERT INTO PROBLEM_CATEGORY (PROBLEM_ID, CATEGORY_ID) VALUES ((SELECT ID FROM PROBLEM WHERE NAME = 'Longest Substring Without Repeating Characters'), (SELECT ID FROM CATEGORY WHERE NAME = 'Two Pointers'));
INSERT INTO PROBLEM_CATEGORY (PROBLEM_ID, CATEGORY_ID) VALUES ((SELECT ID FROM PROBLEM WHERE NAME = 'Median of Two Sorted Arrays'), (SELECT ID FROM CATEGORY WHERE NAME = 'Array'));
INSERT INTO PROBLEM_CATEGORY (PROBLEM_ID, CATEGORY_ID) VALUES ((SELECT ID FROM PROBLEM WHERE NAME = 'Median of Two Sorted Arrays'), (SELECT ID FROM CATEGORY WHERE NAME = 'Binary Search'));
INSERT INTO PROBLEM_CATEGORY (PROBLEM_ID, CATEGORY_ID) VALUES ((SELECT ID FROM PROBLEM WHERE NAME = 'Climbing Stairs'), (SELECT ID FROM CATEGORY WHERE NAME = 'Dynamic Programming'));
INSERT INTO PROBLEM_CATEGORY (PROBLEM_ID, CATEGORY_ID) VALUES ((SELECT ID FROM PROBLEM WHERE NAME = 'Course Schedule'), (SELECT ID FROM CATEGORY WHERE NAME = 'Depth-First Search'));
INSERT INTO PROBLEM_CATEGORY (PROBLEM_ID, CATEGORY_ID) VALUES ((SELECT ID FROM PROBLEM WHERE NAME = 'Course Schedule'), (SELECT ID FROM CATEGORY WHERE NAME = 'Breadth-First Search'));